'use strict';
const { _electron: electron, expect } = require('@playwright/test');
const fs = require('node:fs'), path = require('node:path');
const { startFixture, movie } = require('./fixture.cjs');
(async () => {
  const fixture = await startFixture(), profile = path.resolve('.qa/development-ui-' + Date.now()), checks = [];
  movie.poster = fixture.base + '/qa-art.svg';
  fs.mkdirSync(profile, { recursive: true }); let app, page;
  const pass = step => { checks.push({ step, result: 'PASS' }); console.log('PASS ' + step); };
  const nav = name => page.getByRole('button', { name, exact: true }).click();
  async function settings(name) { await nav('Settings'); await page.getByRole('button', { name: name + ' settings', exact: true }).click(); }
  async function launch() { const env = { ...process.env, NYMORA_DATA_DIR: profile }; delete env.ELECTRON_RUN_AS_NODE; app = await electron.launch({ executablePath: process.env.NYMORA_TEST_EXE || require('electron'), args: process.env.NYMORA_TEST_EXE ? [] : [path.resolve('.')], env, timeout: 45000 }); page = await app.firstWindow(); page.setDefaultTimeout(20000); page.on('pageerror', error => checks.push({ result: 'FAIL', error: error.message })); await expect(page.getByRole('button', { name: 'Home', exact: true })).toBeVisible(); }
  try {
    await launch(); await expect(page.getByRole('status',{name:'Nymora startup'})).toBeVisible(); await expect(page.getByRole('status',{name:'Nymora startup'})).toBeHidden({timeout:2000});
    const initial = await page.evaluate(() => window.nymora.call('state')); expect(initial.settings.p2pWaitMode).toBe('patient'); expect(initial.searchHistory).toEqual([]);
    await expect(page.locator('.sidebar-foot')).toHaveCount(0); pass('Patient mode is default and sidebar footer is removed');
    await nav('Settings'); await expect(page.locator('.settings-category')).toHaveCount(10); await expect(page.locator('.catalog-setting-row')).toHaveCount(0); await page.screenshot({ path: path.join(profile, 'settings.png') }); pass('Settings opens a ten-category landing without catalog controls');
    await page.evaluate(url => window.nymora.call('install', { url }), fixture.base + '/manifest.json');
    await settings('Appearance'); await page.getByLabel('Poster Style', { exact: true }).selectOption('landscape'); await page.getByLabel('Interface Style', { exact: true }).selectOption('glass');
    await nav('Home'); const first = page.locator('.catalog-row .card').first(); await expect(first).toBeVisible();
    const art = await first.locator('.poster').evaluate(n => ({ ratio: getComputedStyle(n).aspectRatio, fit: getComputedStyle(n.querySelector('img')).objectFit })); expect(art.ratio).toBe('16 / 9'); expect(art.fit).toBe('contain'); expect(await page.evaluate(() => document.body.dataset.interfaceStyle)).toBe('glass'); await page.screenshot({ path: path.join(profile, 'glass-landscape.png') }); pass('Landscape artwork keeps portrait proportions and Glass applies without changing catalogs');
    await first.hover(); await expect(page.getByRole('tooltip')).toBeVisible(); await expect(page.getByRole('tooltip')).toContainText(movie.name); await page.mouse.move(15, 40); await expect(page.getByRole('tooltip')).toHaveCount(0); pass('Delayed supplied-metadata preview disappears on pointer leave');
    await nav('Search'); await page.getByLabel('Search titles').fill('Motion'); await page.locator('form.search-form').getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Results for “Motion”' })).toBeVisible();
    await nav('Home'); await nav('Search'); await expect(page.getByRole('heading', { name: 'Recent Searches' })).toBeVisible(); await nav('Motion'); await expect(page.getByRole('heading', { name: 'Results for “Motion”' })).toBeVisible(); pass('Local recent search can be selected to run again');
    await settings('Subtitles & Audio'); await page.getByLabel('Preferred subtitle language').selectOption('ara'); await page.getByLabel('Subtitle appearance').selectOption('box'); await page.getByLabel('Subtitle delay').fill('1.5'); await page.getByLabel('Subtitle delay').dispatchEvent('change'); await page.getByLabel('Preferred audio language').selectOption('eng');
    await settings('Player'); await page.getByLabel('Default volume').fill('0.4'); await page.getByLabel('Default volume').dispatchEvent('change');
    await settings('P2P & Network'); await page.getByLabel('P2P wait time').selectOption('10m');
    await settings('Storage & Cache'); await page.getByLabel('Maximum cache size').selectOption('1024'); await expect(page.getByTestId('cache-size')).toContainText('1.00 GB maximum'); await page.getByRole('button', { name: 'Clear torrent cache' }).click(); pass('Player, subtitle/audio, wait and cache preferences save through validated main operations');
    await nav('Home'); await page.getByRole('button', { name: 'Open ' + movie.name, exact: true }).click(); await nav('Save to Library'); await page.getByRole('button', { name: /Generated MP4/ }).click(); await page.waitForFunction(() => document.querySelector('video')?.getVideoPlaybackQuality().totalVideoFrames > 5);
    expect(await page.locator('video').evaluate(v => v.volume)).toBeCloseTo(.4); await expect(page.getByTestId('subtitle-overlay')).toHaveAttribute('data-appearance', 'box'); await expect(page.getByTestId('subtitle-overlay')).toContainText('الترجمة'); pass('New playback inherits saved volume, subtitle language, timing and appearance');
    await page.locator('.player-layer').focus(); await page.keyboard.press('f'); await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFullScreen())).toBe(true);
    const native = await app.evaluate(({ BrowserWindow, screen }) => { const w = BrowserWindow.getAllWindows()[0]; return { bounds: w.getBounds(), content: w.getContentBounds(), display: screen.getDisplayMatching(w.getBounds()).bounds, fullscreen: w.isFullScreen(), menu: w.isMenuBarVisible() }; }); expect(native.bounds).toEqual(native.display); expect(native.content).toEqual(native.display); expect(native.menu).toBe(false);
    await page.screenshot({ path: path.join(profile, 'native-fullscreen.png') }); pass('Native fullscreen fills display bounds, has zero window frame and no menu bar');
    // Hold for native Windows screenshot inspection only when explicitly enabled.
    if (process.env.NYMORA_NATIVE_INSPECTION === '1') { fs.writeFileSync('.qa/native-inspection-ready.json', JSON.stringify({ profile, native })); await page.waitForFunction(() => window.nymoraInspectionDone === true, null, { timeout: 180000 }); }
    await page.keyboard.press('Escape'); await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFullScreen())).toBe(false);
    const paused = await page.locator('video').evaluate(v => v.paused); await page.locator('video').dblclick({ position: { x: 400, y: 250 } }); await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFullScreen())).toBe(true); expect(await page.locator('video').evaluate(v => v.paused)).toBe(paused); await page.keyboard.press('Escape'); pass('Double-click toggles actual fullscreen without toggling pause; Escape returns');
    await page.getByLabel('Playback position').evaluate(n => { n.value = '20'; n.dispatchEvent(new Event('input', { bubbles: true })); }); await page.mouse.move(600, 300); await page.getByRole('button', { name: 'Exit player' }).click();
    await nav('Home'); await page.getByRole('button', { name: /Remove .* from Continue Watching/ }).click(); await expect(page.locator('.continue-row .card')).toHaveCount(0); expect((await page.evaluate(() => window.nymora.call('state'))).library).toHaveLength(1); await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(page.locator('.continue-row .card')).toHaveCount(1); pass('Continue Watching removal preserves Library and progress; Undo restores it');
    await page.evaluate(m => window.nymora.call('watched', { ...m, mediaId: m.id, watched: true }), movie); await nav('Home'); await expect(page.getByRole('heading', { name: 'Recently Watched', exact: true })).toHaveCount(0); await nav('Library'); await page.getByRole('tab', { name: 'WATCHLIST', exact: true }).click(); await expect(page.getByRole('button', { name: 'Open ' + movie.name })).toBeVisible(); await page.getByRole('tab', { name: 'WATCHED', exact: true }).click(); await expect(page.getByRole('button', { name: 'Open ' + movie.name })).toBeVisible(); await page.screenshot({ path: path.join(profile, 'watched-library.png') }); pass('Watchlist and Watched are distinct; watched history no longer appears on Home');
    await settings('General'); await page.getByLabel('Startup intro', { exact: true }).uncheck(); await page.getByRole('button', { name: 'Preview startup intro' }).click(); await expect(page.getByRole('status', { name: 'Nymora startup' })).toBeVisible(); await expect(page.getByRole('status', { name: 'Nymora startup' })).toBeHidden({ timeout: 2000 });
    const cue = await page.evaluate(async () => { const audio = new Audio('nymora-cue.wav'); audio.volume = .01; await audio.play(); await new Promise(resolve => audio.addEventListener('ended', resolve, { once: true })); return { duration: audio.duration, ended: audio.ended }; }); expect(cue.duration).toBeCloseTo(.86, 2); expect(cue.ended).toBe(true); pass('Optional original intro exits within 1.8s and local sonic logo decodes for 0.86s');
    await app.close(); await launch(); await expect(page.locator('.startup-intro')).toHaveCount(0); await settings('Appearance'); expect(await page.getByLabel('Poster Style').inputValue()).toBe('landscape'); expect(await page.getByLabel('Interface Style').inputValue()).toBe('glass'); await settings('Subtitles & Audio'); expect(await page.getByLabel('Subtitle delay').inputValue()).toBe('1.5'); expect(await page.getByLabel('Preferred audio language').inputValue()).toBe('eng'); await settings('P2P & Network'); expect(await page.getByLabel('P2P wait time').inputValue()).toBe('10m'); await nav('Search'); await expect(page.getByRole('heading', { name: 'Recent Searches' })).toBeVisible(); await page.getByRole('button', { name: 'Clear search history' }).click(); await expect(page.getByRole('heading', { name: 'Recent Searches' })).toHaveCount(0); pass('Appearance, player preferences, waiting, intro and searches survive restart; history clears locally');
    await settings('About'); await expect(page.getByText('Developed by Mohammed Alanazi (M72)', { exact: true })).toBeVisible(); await nav('Open-source notices'); await expect(page.locator('.notices')).toContainText('Stremio'); pass('About preserves authorship and upstream attribution');
    expect(checks.filter(c => c.result === 'FAIL')).toHaveLength(0);
  } catch (error) { checks.push({ result: 'FAIL', error: error.stack }); await page?.screenshot({ path: path.join(profile, 'failure.png') }).catch(() => {}); throw error; }
  finally { fs.writeFileSync(path.join(profile, 'evidence.json'), JSON.stringify({ version: require('../package.json').version, executable: process.env.NYMORA_TEST_EXE || 'development Electron', checks }, null, 2)); await app?.close().catch(() => {}); await fixture.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
