'use strict';
const { _electron:electron, expect }=require('@playwright/test');
const fs=require('node:fs');const path=require('node:path');
const { startPublicFixture }=require('./public-torrent-fixture.cjs');
(async()=>{
  const fixture=await startPublicFixture();const profile=path.resolve('.qa/public-installed-'+Date.now());fs.mkdirSync(profile,{recursive:true});
  const evidence={version:require('../package.json').version,time:new Date().toISOString(),source:fixture.source,proof:'Only infoHash, trackers and file hints. No HTTP .torrent, xs/as/ws, HTTP video or self-seeder.',checks:[]};let app,page;
  const pass=(step,details)=>{evidence.checks.push({step,result:'PASS',details});console.log('PASS '+step,details||'');};
  async function launch(){const env={...process.env,NYMORA_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;delete env.NYMORA_P2P_TEST_MODE;app=await electron.launch({executablePath:process.env.NYMORA_TEST_EXE||require('electron'),args:process.env.NYMORA_TEST_EXE?[]:[path.resolve('.')],env,timeout:45000});page=await app.firstWindow();page.setDefaultTimeout(90000);await expect(page.getByRole('button',{name:'Addons',exact:true})).toBeVisible();}
  const status=()=>page.evaluate(()=>window.nymora.call('playbackStatus'));
  async function select(){await page.locator('button.source').first().click();await expect(page.getByRole('dialog',{name:'P2P Streaming Notice'})).toBeVisible();}
  async function decode(position=0){await page.waitForFunction(p=>{const v=document.querySelector('video');return v&&v.videoWidth>0&&v.currentTime>p&&v.getVideoPlaybackQuality().totalVideoFrames>3&&!v.paused;},position,{timeout:360000});return page.locator('video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,position:v.currentTime,duration:v.duration,frames:v.getVideoPlaybackQuality().totalVideoFrames}));}
  try{
    await launch();evidence.executable=process.env.NYMORA_TEST_EXE?path.basename(process.env.NYMORA_TEST_EXE):'development Electron';evidence.runtime=await app.evaluate(({app})=>({version:app.getVersion(),packaged:app.isPackaged,electron:process.versions.electron,chromium:process.versions.chrome}));
    for(const url of [fixture.base+'/manifest.json',fixture.base+'/broken/manifest.json'])await page.evaluate(url=>window.nymora.call('install',{url}),url);
    await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Open '+fixture.movie.name}).click();await expect(page.locator('button.source')).toHaveCount(1);
    await expect(page.getByRole('heading',{name:'Watch / Sources'})).toBeVisible();await expect(page.locator('.sources .addon-warning')).toContainText('HTTP 503');
    expect(fixture.requests.find(r=>r.url.startsWith('/stream/')).time-fixture.requests.find(r=>r.url.startsWith('/meta/')).time).toBeLessThan(600);
    expect(await page.evaluate(()=>document.querySelector('.title-actions').compareDocumentPosition(document.querySelector('.sources'))&Node.DOCUMENT_POSITION_FOLLOWING)).toBeTruthy();pass('Movie sources queried before metadata; hero actions remain above sources and failed addons leave working sources');
    await select();expect((await status()).startedSessions).toBe(0);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog',{name:'Preparing playback'})).toBeHidden();expect((await status()).startedSessions).toBe(0);pass('Cancel starts zero P2P sessions');
    await select();await page.getByRole('button',{name:'I Understand — Play',exact:true}).click();const first=await decode(.3);evidence.discovery=await status();expect(evidence.discovery.metadataState).toBe('received');expect(evidence.discovery.downloaded).toBeGreaterThan(0);expect(evidence.discovery.rangeRequests).toBeGreaterThan(0);expect(first.width).toBe(1024);pass('Existing internet peers supply metadata, selected video, buffering, loopback Range bytes and decoded player frames',first);
    await page.mouse.move(600,300);await page.getByRole('button',{name:'Pause',exact:true}).click();expect(await page.locator('video').evaluate(v=>v.paused)).toBe(true);await page.getByRole('button',{name:'Play',exact:true}).click();await decode(first.position+.2);pass('Pause/resume');
    await page.getByLabel('Playback position').evaluate(node=>{node.value='180';node.dispatchEvent(new Event('input',{bubbles:true}));});const sought=await decode(180.2);expect((await status()).lastRangeStart).toBeGreaterThan(0);pass('Seek reprioritizes distant peer pieces and decodes',sought);
    await page.mouse.move(610,300);await page.getByRole('button',{name:'Subtitles',exact:true}).click();
    for(const lang of ['English','Arabic']){await page.getByLabel('Subtitle track').selectOption({label:lang==='English'?'English · original QA cues · Legal public peer test':'Arabic · العربية · original QA cues · Legal public peer test'});await expect(page.getByTestId('subtitle-overlay')).toContainText(lang==='English'?'Original QA subtitle':'ترجمة اختبار');}await page.getByLabel('Subtitle track').selectOption('');await expect(page.getByTestId('subtitle-overlay')).toBeEmpty();pass('English, Arabic and Off subtitles use exact movie ID');
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.join(profile,'local.srt'));fs.writeFileSync(path.join(profile,'local.srt'),'1\n00:00:00,000 --> 00:15:00,000\nOriginal local QA subtitle\n');await page.getByRole('button',{name:'Local subtitle',exact:true}).click();await expect(page.getByTestId('subtitle-overlay')).toContainText('Original local QA');pass('Local subtitle remains available');
    evidence.diagnostics=await page.evaluate(()=>window.nymora.call('copyP2PDiagnostics'));expect(JSON.stringify(evidence.diagnostics)).not.toMatch(/Authorization|127\.0\.0\.1|cookie|\/torrent\//i);
    fs.mkdirSync('.qa/development/screenshots',{recursive:true});await page.screenshot({path:'.qa/development/screenshots/public-p2p-playback-1.0.2.png'});
    const url=await page.locator('video').evaluate(v=>v.src);await page.mouse.move(620,300);await page.locator('.player-layer').focus();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Exit player',exact:true}).click();expect(await fetch(url).catch(()=>null)).toBeNull();expect(JSON.parse(fs.readFileSync(path.join(profile,'nymora.json'))).progress['movie:'+fixture.movie.id].position).toBeGreaterThan(180);pass('Exit stops peers/endpoint and saves progress');
    await app.close();await launch();await page.getByRole('button',{name:'Open '+fixture.movie.name}).first().click();await expect(page.getByLabel('Resume saved progress')).toBeChecked();await page.locator('button.source').first().click();await expect(page.getByRole('dialog',{name:'P2P Streaming Notice'})).toBeHidden();expect(JSON.parse(fs.readFileSync(path.join(profile,'nymora.json'))).p2pNoticeAccepted).toBe(true);pass('Reopened profile remembers acknowledgement and resumes public torrent',await decode(180));
    await app.close();app=null;expect(fixture.requests.some(r=>r.url.startsWith('/subtitles/movie/'+encodeURIComponent(fixture.movie.id)))).toBe(true);pass('Complete public internet P2P client path');evidence.result='PASS';
  }catch(error){evidence.result='FAIL';evidence.error=error.message;if(page){evidence.discovery=await status().catch(()=>null);evidence.video=await page.locator('video').evaluate(v=>({paused:v.paused,readyState:v.readyState,time:v.currentTime,frames:v.getVideoPlaybackQuality().totalVideoFrames,error:v.error?.code})).catch(()=>null);await page.screenshot({path:'.qa/public-p2p-failure.png'}).catch(()=>{});}throw error;}finally{fs.writeFileSync(path.join(profile,'evidence.json'),JSON.stringify(evidence,null,2));if(evidence.result==='PASS')fs.writeFileSync('.qa/development/public-p2p-evidence.json',JSON.stringify(evidence,null,2));await app?.close().catch(()=>{});await fixture.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
