'use strict';
const { _electron: electron, expect } = require('@playwright/test');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { startFixture, movie, series } = require('./fixture.cjs');
async function main() {
  const fixture = await startFixture(); let base, app, page;
  const profile = path.resolve(`.qa/ui-${Date.now()}`), screenshots = path.join(profile, 'screenshots'), checks = [], requests = [];
  fs.mkdirSync(screenshots, { recursive: true });
  const server = http.createServer((req, res) => {
    const url = new URL(req.url, 'http://localhost'); requests.push(url.pathname);
    res.setHeader('Access-Control-Allow-Origin', '*');
    if (url.pathname.endsWith('.svg')) { res.setHeader('Content-Type', 'image/svg+xml'); return res.end('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="700"><defs><linearGradient id="g"><stop stop-color="#183c35"/><stop offset="1" stop-color="#153246"/></linearGradient></defs><path fill="url(#g)" d="M0 0h1200v700H0z"/><circle cx="800" cy="270" r="190" fill="#82dfbc" opacity=".14"/><path d="M0 650L500 250l250 250 300-400 150 600" fill="#264d46"/><text x="60" y="600" fill="#a6e6d1" font-size="40">Original Nymora QA artwork</text></svg>'); }
    res.setHeader('Content-Type', 'application/json');
    const send = value => res.end(JSON.stringify(value));
    if (url.pathname === '/manifest.json') return send({ id: 'org.nymora.ui-metadata', name: 'UI metadata study', version: '1.0.0', description: 'Original metadata and artwork for development checks.', types: ['movie', 'series', 'person'], resources: ['meta', 'stream'], catalogs: [] });
    const id = decodeURIComponent(url.pathname.split('/')[3]?.replace(/\.json$/, '') || '');
    if (url.pathname.startsWith('/stream/')) return send({ streams: id.startsWith('opaque/') ? ['mp4', 'webm', 'm3u8'].map(ext => ({ name: 'Original UI ' + ext, url: fixture.base + '/media/test.' + ext })) : [] });
    if (url.pathname.startsWith('/meta/person/')) return send({ meta: { id, type: 'person', name: 'QA Performer', bio: 'An original development fixture profile, supplied by the metadata provider.', knownMovies: [movie], knownSeries: [series] } });
    if (url.pathname.startsWith('/meta/')) {
      const title = id === series.id ? series : movie;
      return send({ meta: { ...title, description: title.description + ' This longer complete synopsis is provided by a second addon. '.repeat(8), poster: base + '/poster.svg', background: base + '/backdrop.svg', imdbRating: '8.4', cast: [{ id: 'qa-person:1', name: 'QA Performer', character: 'Motion artist', portrait: base + '/portrait.svg' }, 'Name-only performer'], videos: title.type === 'series' ? Array.from({ length: 1001 }, (_, i) => ({ id: `opaque/ui episode ${i + 1}`, season: 1, episode: i + 1, title: `Motion ${i + 1}`, thumbnail: base + '/episode.svg', runtime: '90 seconds', released: '2026-01-02', rating: '8.1' })) : undefined } });
    }
    res.writeHead(404); res.end();
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); base = `http://127.0.0.1:${server.address().port}`;
  const pass = step => { checks.push({ step, result: 'PASS' }); console.log('PASS ' + step); };
  const nav = name => page.getByRole('button', { name, exact: true }).click();
  async function launch() {
    const env = { ...process.env, NYMORA_DATA_DIR: profile }; delete env.ELECTRON_RUN_AS_NODE;
    app = await electron.launch({ executablePath: process.env.NYMORA_TEST_EXE || require('electron'), args: process.env.NYMORA_TEST_EXE ? [] : [path.resolve('.')], env, timeout: 45000 });
    page = await app.firstWindow(); page.setDefaultTimeout(15000); page.on('pageerror', e => checks.push({ result: 'FAIL', error: e.message }));
    await expect(page.getByRole('button', { name: 'Home', exact: true })).toBeVisible();
  }
  try {
    await launch();
    const state = await page.evaluate(() => window.nymora.call('state')); expect(state.addons).toHaveLength(0); pass('No silent default addon installation');
    for (const url of [fixture.base + '/manifest.json', base + '/manifest.json']) await page.evaluate(url => window.nymora.call('install', { url }), url);
    await nav('Home'); await page.getByRole('button', { name: 'Open ' + movie.name }).click();
    await expect(page.locator('.description')).toContainText('second addon'); await expect(page.locator('.cast-card')).toHaveCount(2); await page.getByRole('button', { name: 'More', exact: true }).click(); await expect(page.locator('.description')).toHaveClass(/expanded/);
    await page.screenshot({ path: path.join(screenshots, 'movie.png') }); pass('Richer complete synopsis, backdrop, rating and cast presentation');
    await page.getByRole('button', { name: /QA Performer/ }).click(); await expect(page.getByRole('heading', { name: 'Known movies' })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Known series' })).toBeVisible(); await expect(page.locator('.description')).toContainText('original development fixture profile'); await page.screenshot({ path: path.join(screenshots, 'person.png') });
    await page.getByRole('button', { name: 'Back to title' }).click(); pass('Stable person ID opens only supplied biography and known titles');
    await page.getByRole('button', { name: /Generated MP4/ }).click();
    await page.waitForFunction(() => document.querySelector('video')?.getVideoPlaybackQuality().totalVideoFrames > 5);
    await page.locator('.player-layer').focus();
    const bounds = await page.locator('video').boundingBox(), viewport = page.viewportSize() || await page.evaluate(() => ({ width: innerWidth, height: innerHeight })); expect(Math.abs(bounds.width - viewport.width)).toBeLessThan(1); expect(Math.abs(bounds.height - viewport.height)).toBeLessThan(1); expect(await page.locator('video').evaluate(v => getComputedStyle(v).objectFit)).toBe('contain'); pass('Player video occupies the full app viewport and keeps aspect ratio');
    await page.mouse.move(600, 300); await expect(page.locator('.player-layer')).toHaveClass(/controls-hidden/, { timeout: 5000 }); await page.mouse.move(610, 300); await expect(page.locator('.player-layer')).not.toHaveClass(/controls-hidden/); pass('Controls hide after idle and return on mouse movement');
    await page.getByRole('button', { name: 'Pause', exact: true }).click(); await page.getByRole('button', { name: 'Play', exact: true }).click(); await page.mouse.move(630, 300); await expect(page.locator('.player-layer')).toHaveClass(/controls-hidden/, { timeout: 5000 }); await page.mouse.move(640, 300); await page.locator('.player-layer').focus(); pass('Controls still hide after mouse interaction leaves a button focused');
    await page.keyboard.press('Space'); expect(await page.locator('video').evaluate(v => v.paused)).toBe(true); await page.keyboard.press('Space'); expect(await page.locator('video').evaluate(v => v.paused)).toBe(false);
    await page.getByRole('button', { name: 'Player settings', exact: true }).click(); await page.getByLabel('Playback speed').selectOption('1.5'); await page.locator('.player-layer').focus(); await page.keyboard.press('Escape');
    await page.keyboard.down('Space'); await expect(page.getByTestId('speed-indicator')).toBeVisible(); expect(await page.locator('video').evaluate(v => v.playbackRate)).toBe(2); await page.keyboard.down('Space'); await page.keyboard.up('Space'); expect(await page.locator('video').evaluate(v => v.playbackRate)).toBe(1.5); expect(await page.locator('video').evaluate(v => v.paused)).toBe(false); pass('Short Space toggles; held/repeated Space restores previous speed without pause');
    await page.keyboard.down('Space'); await expect(page.getByTestId('speed-indicator')).toBeVisible(); await page.evaluate(() => window.dispatchEvent(new Event('blur'))); expect(await page.locator('video').evaluate(v => v.playbackRate)).toBe(1.5); await page.keyboard.up('Space'); pass('Lost focus restores temporary playback speed');
    await page.locator('video').evaluate(v => { v.currentTime = 30; }); await page.keyboard.press('ArrowRight'); await expect(page.getByTestId('seek-feedback')).toContainText('10s ↷'); expect(await page.locator('video').evaluate(v => v.currentTime)).toBeGreaterThanOrEqual(40); await page.keyboard.press('ArrowLeft'); expect(await page.locator('video').evaluate(v => v.currentTime)).toBeLessThan(32);
    const volume = await page.locator('video').evaluate(v => v.volume); await page.keyboard.press('ArrowDown'); expect(await page.locator('video').evaluate(v => v.volume)).toBeCloseTo(volume - .05); await page.keyboard.press('ArrowUp'); await page.keyboard.press('m'); expect(await page.locator('video').evaluate(v => v.muted)).toBe(true); await page.keyboard.press('m'); pass('Arrow seek feedback, volume and mute shortcuts');
    await page.keyboard.press('f'); await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFullScreen())).toBe(true); await page.keyboard.press('Escape'); await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isFullScreen())).toBe(false); await expect(page.locator('.player-layer')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.locator('.player-layer')).toBeVisible(); pass('F fullscreen and Escape preserve the player session');
    await page.getByRole('button', { name: 'Subtitles', exact: true }).click(); await page.getByLabel('Subtitle delay').focus(); const before = await page.locator('video').evaluate(v => v.currentTime); await page.keyboard.press('ArrowRight'); expect(await page.locator('video').evaluate(v => v.currentTime)).toBeLessThan(before + 3); await page.keyboard.press('Space'); expect(await page.locator('video').evaluate(v => v.paused)).toBe(false);
    await page.evaluate(() => { const field = document.createElement('textarea'); field.setAttribute('aria-label', 'QA text field'); document.querySelector('.player-menu:not([hidden])').append(field); field.focus(); }); await page.keyboard.press('Space'); expect(await page.locator('video').evaluate(v => v.paused)).toBe(false); await page.getByLabel('QA text field').evaluate(n => n.remove()); pass('Shortcuts ignore numeric fields, selects and textareas');
    await page.getByLabel('Subtitle track').selectOption({ label: 'Arabic · العربية · original test · Nymora legal test addon' }); await expect(page.getByTestId('subtitle-overlay')).toContainText('ترجمة'); await page.locator('.player-layer').focus(); await page.keyboard.press('Escape'); await page.screenshot({ path: path.join(screenshots, 'player.png') });
    await page.getByRole('button', { name: 'Exit player', exact: true }).click();
    await nav('Settings'); const rows = page.locator('.catalog-setting-row'); await rows.first().getByRole('button', { name: 'Move Down' }).click(); await rows.first().getByRole('button', { name: 'Hide row' }).click(); await page.getByLabel('Blur episode thumbnails').check();
    await nav('Home'); await expect(page.locator('main > section').first().getByRole('heading', { name: 'Continue Watching' })).toBeVisible(); await expect(page.locator('.catalog-row')).toHaveCount(1); pass('Home reorder/hide keeps Continue Watching above all catalogs');
    await app.close(); await launch(); await nav('Settings'); expect(await page.getByLabel('Blur episode thumbnails').isChecked()).toBe(true); await expect(page.locator('.catalog-setting-row').first().getByRole('button', { name: 'Show row' })).toBeVisible(); await page.getByRole('button', { name: 'Reset layout' }).click(); await expect(page.locator('.catalog-setting-row').first()).toContainText('movie'); pass('Catalog order, visibility and spoiler settings survive restart; reset restores order');
    await nav('Home'); await page.getByRole('button', { name: 'Open ' + series.name }).click(); await page.getByLabel('Season').selectOption('1'); await expect(page.locator('.episode-row')).toHaveCount(24); await expect(page.getByLabel('Episode page')).toBeVisible(); await page.getByLabel('Episode page').selectOption('41'); await expect(page.getByRole('button', { name: /^1001\. Motion 1001/ })).toBeVisible(); expect(await page.locator('.spoiler-blur img').first().evaluate(n => getComputedStyle(n).filter)).toBe('blur(20px)'); await page.screenshot({ path: path.join(screenshots, 'episodes.png') });
    await page.getByRole('button', { name: /^1001\. Motion 1001/ }).click(); await expect(page.getByRole('heading', { name: 'Motion 1001', exact: true })).toBeVisible(); await expect(page.locator('.episode-section')).toBeHidden(); await expect(page.locator('button.source')).toHaveCount(3); expect(requests.some(r => r.includes('/stream/series/opaque%2Fui%20episode%201001.json'))).toBe(true); await page.screenshot({ path: path.join(screenshots, 'episode-sources.png') }); await page.getByRole('button', { name: 'Back to Episodes' }).click(); expect(await page.getByLabel('Episode page').inputValue()).toBe('41'); pass('1001 episodes render in bounded chunks; dedicated sources preserve opaque episode ID and page on return');
    await nav('Settings'); await expect(page.getByText('Developed by Mohammed Alanazi (M72)', { exact: true })).toBeVisible(); pass('About includes requested authorship and preserved upstream notices');
    // Isolate UI acceptance from peer availability; real internet P2P has its own suite.
    async function stubEngine() { await app.evaluate(({ app }) => { const req = process.getBuiltinModule('module').createRequire(app.getAppPath() + '/package.json'); globalThis.uiStarts = 0; req('./src/torrent-engine.cjs').TorrentEngine.prototype.start = async function() { globalThis.uiStarts++; throw new Error('QA stopped discovery after consent gate'); }; }); }
    await stubEngine();
    await page.evaluate(() => window.nymora.call('settings', { p2pNoticeAccepted: true }));
    expect((await page.evaluate(() => window.nymora.call('state'))).p2pNoticeAccepted).toBe(false);
    expect(await page.evaluate(() => window.nymora.call('p2pNoticeAnswer', { nonce: 'forged', accepted: true }).then(() => false, () => true))).toBe(true);
    async function requestP2P() { await page.evaluate(() => { window.nymora.call('source', { infoHash: 'a'.repeat(40), consent: true }).catch(() => {}); }); }
    await requestP2P(); await expect(page.getByRole('dialog', { name: 'P2P Streaming Notice' })).toBeVisible(); expect(await app.evaluate(() => globalThis.uiStarts)).toBe(0); await page.screenshot({ path: path.join(screenshots, 'consent.png') }); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); expect((await page.evaluate(() => window.nymora.call('state'))).p2pNoticeAccepted).toBe(false);
    await requestP2P(); await expect(page.getByRole('dialog', { name: 'P2P Streaming Notice' })).toBeVisible(); await page.getByRole('button', { name: 'I Understand — Play', exact: true }).click(); await expect.poll(() => app.evaluate(() => globalThis.uiStarts)).toBe(1); expect((await page.evaluate(() => window.nymora.call('state'))).p2pNoticeAccepted).toBe(true); await requestP2P(); await expect.poll(() => app.evaluate(() => globalThis.uiStarts)).toBe(2); await expect(page.getByRole('dialog', { name: 'P2P Streaming Notice' })).toBeHidden(); pass('Custom notice blocks engine before acceptance; Cancel does not persist; subsequent sessions omit accepted notice');
    await app.close(); await launch(); await stubEngine(); await requestP2P(); await expect.poll(() => app.evaluate(() => globalThis.uiStarts)).toBe(1); await expect(page.getByRole('dialog', { name: 'P2P Streaming Notice' })).toBeHidden(); await nav('Settings'); await page.getByRole('button', { name: 'Reset P2P warning' }).click(); await requestP2P(); await expect(page.getByRole('dialog', { name: 'P2P Streaming Notice' })).toBeVisible(); await page.keyboard.press('Escape'); expect(await app.evaluate(() => globalThis.uiStarts)).toBe(1); pass('Acknowledgement survives restart; Reset and Escape restore/cancel the notice');
    expect(checks.filter(c => c.result === 'FAIL')).toHaveLength(0);
  } catch (error) { checks.push({ result: 'FAIL', error: error.stack }); await page?.screenshot({ path: path.join(screenshots, 'failure.png') }).catch(() => {}); throw error; }
  finally { fs.writeFileSync(path.join(profile, 'evidence.json'), JSON.stringify({ version: require('../package.json').version, executable: process.env.NYMORA_TEST_EXE || 'development Electron', checks, requests }, null, 2)); await app?.close().catch(() => {}); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); await fixture.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
