[package]
name = "nymora-torrent-helper"
version = "1.0.2"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
librqbit = { git = "https://github.com/ikatson/rqbit", rev = "a499d2f243d124e144aef137afe7cb304a6e3f36", default-features = false, features = ["rust-tls", "http-api", "tracing-subscriber-utils"] }
librqbit-dualstack-sockets = { version = "=0.7.0", features = ["axum"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
anyhow = "1"
base64 = "0.22"

[profile.release]
strip = true
lto = "thin"
