// Presentation only. Main validates all saved preferences and owns P2P consent.
globalThis.NymoraSettings = (() => {
  const categories = [
    ['General', 'Startup and local preferences'], ['Appearance', 'Posters, surfaces and spoiler protection'], ['Home', 'Catalog order and hidden rows'], ['Player', 'Playback defaults'], ['Subtitles & Audio', 'Languages, timing and appearance'], ['P2P & Network', 'Waiting and your P2P acknowledgement'], ['Storage & Cache', 'Usage, limits and inactive cache cleanup'], ['Privacy / History', 'Local search history and Continue Watching visibility'], ['About', 'Nymora, licenses and attribution']
  ];
  async function save(value) { state = await call('settings', value); applyAppearance(); }
  function select(label, key, options) {
    const node = el('select', { 'aria-label': label }, options.map(([value, name]) => el('option', { value }, name)));
    if (![...node.options].some(o => o.value === String(state.settings[key]))) node.append(el('option', { value: state.settings[key] }, state.settings[key]));
    node.value = state.settings[key]; node.addEventListener('change', () => save({ [key]: node.value }).catch(e => toast(e.message)));
    return el('label', {}, label, node);
  }
  function toggle(label, key) { const node = el('input', { type: 'checkbox', 'aria-label': label, checked: state.settings[key], onchange: () => save({ [key]: node.checked }).catch(e => toast(e.message)) }); return el('label', { className: 'toggle-setting' }, node, label); }
  function number(label, key, min, max, step = 1, type = 'number') {
    const node = el('input', { type, min, max, step, value: state.settings[key], 'aria-label': label, onchange: async () => { try { await save({ [key]: Number(node.value) }); node.value = state.settings[key]; } catch (e) { toast(e.message); } } }); return el('label', {}, label, node);
  }
  const languages = () => ['eng', 'ara', 'spa', 'fra', 'deu', 'jpn', 'por', 'rus', 'hin', 'zho'].map(code => [code, languageName(code)]);
  async function show(content, category, renderCatalogs, changeCategory) {
    const area = el('div', { className: 'settings-view' }); content.append(area);
    async function open(name) {
      area.replaceChildren();
      if (!name) {
        const grid = el('div', { className: 'settings-grid' }); area.append(el('p', { className: 'muted' }, 'Make Nymora feel at home. Preferences stay on this device.'), grid);
        for (const [title, caption] of categories) { const node = button([el('strong', {}, title), el('span', { className: 'muted' }, caption), el('span', { className: 'category-arrow', 'aria-hidden': 'true' }, '↗')], () => changeCategory(title), 'settings-category'); node.setAttribute('aria-label', title + ' settings'); grid.append(node); } return;
      }
      area.append(el('h2', { className: 'settings-title' }, name));
      const panel = el('section', { className: 'panel settings' }); area.append(panel);
      if (name === 'General') panel.append(toggle('Startup intro', 'startupIntro'), toggle('Startup sound', 'startupSound'), el('p', { className: 'muted' }, 'A short original Nymora animation and sonic signature. Sound is off by default.'), button('Preview startup intro', () => showIntro(true)), button('Preview startup sound', playStartupSound, 'button subtle'));
      if (name === 'Appearance') panel.append(select('Poster Style', 'posterStyle', [['portrait', 'Portrait'], ['landscape', 'Landscape']]), select('Interface Style', 'interfaceStyle', [['classic', 'Classic'], ['glass', 'Glass']]), toggle('Blur episode thumbnails', 'blurEpisodeThumbnails'), el('p', { className: 'muted' }, 'Landscape uses supplied backdrops; portrait-only artwork keeps its proportions. Glass automatically reduces blur if rendering slows down. Episode blur protects against visual spoilers.'));
      if (name === 'Home') { panel.remove(); await renderCatalogs(area); }
      if (name === 'Player') panel.append(select('Default Video Fit', 'videoFit', [['fit', 'Fit'], ['fill', 'Fill'], ['original', 'Original']]), el('p', { className: 'muted' }, 'Fit shows the whole image; different aspect ratios may leave black bars. Fill crops to fill the screen. Original keeps source dimensions when they fit. No mode stretches the image.'), toggle('Start playback fullscreen', 'startFullscreen'), select('Skip interval', 'skipInterval', [5, 10, 15, 30].map(n => [n, n + ' sec'])), select('Player controls auto-hide', 'controlsHideSeconds', [[2, '2 sec'], [3, '3 sec'], [5, '5 sec'], [0, 'Never']]), toggle('Hold Space for 2×', 'holdSpace2x'), select('Default playback speed', 'defaultPlaybackSpeed', [.5, .75, 1, 1.25, 1.5, 2].map(n => [n, n + '×'])), toggle('Autoplay next episode', 'autoplayNextEpisode'), select('Resume playback', 'resumePlayback', [['ask', 'Ask'], ['resume', 'Always Resume'], ['restart', 'Always Start Over']]), toggle('Show P2P statistics in player', 'showP2PStats'), number('Default volume', 'volume', 0, 1, .05, 'range'), el('p', { className: 'muted' }, 'Space: play/pause · Hold Space: temporary 2× when enabled · Left/Right: chosen skip interval · Up/Down: volume · M: mute · F: native fullscreen · Double click video: fullscreen · Escape: exit fullscreen or close menus. Shortcuts pause while you type. Autoplay uses the next supplied episode and a matching provider/source when available.'));
      if (name === 'Subtitles & Audio') panel.append(select('Preferred subtitle language', 'subtitleLanguage', languages()), number('Subtitle size', 'subtitleSize', 16, 72, 1, 'range'), number('Subtitle delay', 'subtitleDelay', -120, 120, .5), select('Subtitle appearance', 'subtitleAppearance', [['shadow', 'Soft shadow'], ['outline', 'High contrast outline'], ['box', 'Translucent background']]), select('Preferred audio language', 'audioLanguage', [['', 'Source default'], ...languages()]), el('p', { className: 'muted' }, 'Saved preferences apply to new playback sessions. Arabic and English use automatic text direction. Audio language applies when the stream exposes language-labelled tracks. ASS/SSA authored styling is displayed as plain text.'));
      if (name === 'Privacy / History') panel.append(el('p', {}, 'Watchlist, progress and searches stay on this device. Nymora sends no analytics. Continue Watching visibility is independent of Watchlist and Watched.'), button('Restore Continue Watching items', async () => { state = await call('dismissContinuing', { reset: true }); toast('Continue Watching items restored.'); }, 'button subtle'), button('Clear search history', async () => { state = await call('recentSearch', { clear: true }); toast('Search history cleared.'); }, 'button subtle'));
      if (name === 'P2P & Network') panel.append(select('P2P wait time', 'p2pWaitMode', [['patient', 'Patient mode (recommended)'], ['5m', '5 minutes'], ['10m', '10 minutes'], ['none', 'No automatic timeout']]), el('p', { className: 'muted' }, 'Patient mode continues discovery while the engine is healthy. Slow or few peers do not reject a source. Cancel is always available. Finite limits apply to preparation and subsequent stream inactivity; fatal source or engine errors still stop playback.'), el('p', { 'data-testid': 'consent-setting' }, state.p2pNoticeAccepted ? 'P2P notice acknowledged on this device.' : 'The P2P notice will appear before your next P2P source.'), button('Reset P2P warning', async () => { state = await call('resetP2PNotice'); toast('P2P warning reset.'); await open(name); }, 'button subtle'), el('p', { className: 'muted' }, 'The notice is informational. It does not grant content rights. Third-party addons and sources remain independently provided.'));
      if (name === 'Storage & Cache') {
        const summary = await call('cacheSummary'), usage = el('p', { 'data-testid': 'cache-size' });
        const custom = el('input', { type: 'number', min: 256, max: 16384, step: 1, value: summary.limitMB, 'aria-label': 'Torrent cache limit (MB)' });
        const limits = [1024, 2048, 5120, 10240], preset = el('select', { 'aria-label': 'Maximum cache size' }, limits.map(value => el('option', { value }, `${value / 1024} GB`)), el('option', { value: 'custom' }, 'Custom'));
        preset.value = limits.includes(summary.limitMB) ? String(summary.limitMB) : 'custom';
        const refresh = async () => { const s = await call('cacheSummary'); usage.textContent = `${(s.bytes / 1024 ** 3).toFixed(2)} GB cached / ${(s.limitMB / 1024).toFixed(2)} GB maximum${s.active ? ' · Active playback protected' : ''}`; custom.parentElement.hidden = preset.value !== 'custom'; };
        preset.addEventListener('change', async () => { try { if (preset.value !== 'custom') { custom.value = preset.value; await save({ torrentCacheMB: Number(preset.value) }); } await refresh(); } catch (e) { toast(e.message); } });
        panel.append(usage, el('label', {}, 'Maximum cache size', preset), el('label', {}, 'Custom limit (MB)', custom), el('div', { className: 'actions' }, button('Save cache limit', async () => { await save({ torrentCacheMB: Number(custom.value) }); await refresh(); }), button('Refresh cache size', refresh, 'button subtle'), button('Clear torrent cache', async () => { await call('clearTorrentCache'); await refresh(); toast('Inactive torrent cache cleared.'); }, 'button subtle')), el('p', { className: 'muted' }, 'Oldest inactive sessions are removed automatically to fit the budget. Active playback data is never cleared. Custom limits: 256–16384 MB. A selected video and its boundary pieces must fit the limit.'), el('p', { className: 'mono muted' }, state.dataDirectory)); await refresh();
      }
      if (name === 'About') {
        const notices = el('pre', { className: 'notices', hidden: true }); panel.append(el('div', { className: 'wordmark' }, el('img', { src: 'logo.svg', alt: '', width: 40 }), el('h2', {}, 'NYMORA')), el('p', { className: 'author-credit' }, 'Developed by Mohammed Alanazi (M72)'), el('p', {}, 'Copyright © 2026 Mohammed Alanazi'), el('p', {}, `Version ${state.appVersion}`), el('p', {}, 'Independent open-source media client. Not affiliated with, sponsored by, or endorsed by Stremio.'), el('p', {}, 'Original Nymora code: MIT. Stremio addon-client, WebTorrent and Electron retain their MIT licenses and upstream copyrights. Chromium, hls.js and native librqbit retain their respective bundled licenses and notices.'), el('div', { className: 'actions' }, button('GitHub repository', () => call('external', { url: 'https://github.com/igc27/Nymora' })), button('Open-source notices', async () => { notices.textContent = await call('notices'); notices.hidden = !notices.hidden; })), notices, el('p', { className: 'muted' }, 'No analytics. Media processing is free and local. HTTP(S), HLS and BitTorrent v1 sources use the internal player; availability and compatible codecs depend on the source. DRM and BitTorrent v2-only sources are unsupported.'));
      }
    }
    await open(category);
  }
  return { show };
})();
